# Test Command: ansible-playbook --user=vagrant --ask-pass --inventory-file=octagon-hosts.yml octagon-playbook.yml

- hosts: all
  become: true
  vars:
    files_dir: files/
    apache_files_dir: '{{ files_dir }}apache/'
    ldap_files_dir: '{{ files_dir }}ldap/'
    lab_files_dir: '{{ files_dir }}labs/'
  vars_files: 
    - vars/octagon-variables.yml
  environment:
    ansible_python_interpreter: '/usr/bin/python3'

  tasks:
  - name: Change Linux root password to mutillidae
    user: 
      name: root
      update_password: always
      password: '{{ linux_password }}'

  - name: Add mutillidae.local domain to /etc/hosts
    lineinfile:
      path: /etc/hosts
      regexp: '^127.0.0.1'
      line: '127.0.0.1	{{ website_domain_name }} {{ website_domain_aliases }}'

  - name: Update APT cache
    apt: 
      update_cache: yes

  - name: Install aptitude for ansible to use
    apt: 
      name: ['aptitude', 'python-apt']
      state: latest
      force_apt_get: yes
 
  - name: Install Packages
    apt:
      name: ['apache2', 'libapache2-mod-php', 'mariadb-client', 'mariadb-common', 'mariadb-server', 'default-libmysqlclient-dev', 'php', 'php-mysql', 'php-curl', 'php-mbstring', 'php-xml', 'python3-pip', 'python3-setuptools', 'python3-virtualenv', 'python3-dev', 'python3-mysqldb', 'python3-pymysql']
      state: latest

  - name: Remove JavaScript-Common package
    apt:
      name: javascript-common
      state: absent

  - name: Remove useless packages from the cache
    apt:
      autoclean: yes

  - name: Remove dependencies that are no longer required
    apt:
      autoremove: yes

  #Install Mutillidae
  - name: Clone Mutillidae from GitHub
    git:
      repo: '{{ mutillidae_git_repo }}'
      dest: '{{ www_path }}{{ website_name }}'
      update: yes
      force: yes

  #Apache Configuration
  - name: Copy SSL certificate and private key
    copy:
      src:    '{{ item.src }}'
      dest:   '{{ item.dest }}'
      owner:  root
      group:  root
      mode:   '{{ item.mode }}'
    with_items:
      - src:  '{{ apache_files_dir }}{{ ssl_certificate }}'
        dest: '{{ ssl_certs_dir }}{{ ssl_certificate }}'
        mode: '0644'
      - src:  '{{ apache_files_dir }}{{ ssl_private_key }}'
        dest: '{{ ssl_private_key_dir }}{{ ssl_private_key }}'
        mode: '0600'

  - name: Enable ssl module
    apache2_module:
      state: present
      name: ssl
    notify: Restart Apache

  - name: Set up Apache virtualhost
    template:
      src: '{{ apache_files_dir }}{{ http_conf }}.j2'
      dest: '/etc/apache2/sites-available/{{ http_conf }}'
    notify: Reload Apache

  - name: Enable Mutillidae site
    shell: '{{ a2ensite }} {{ http_conf }}'
    notify: Reload Apache

  - name: Disable default Apache site
    shell: '{{ a2dissite }} 000-default.conf'
    when: disable_default
    notify: Reload Apache

  - name: Start Apache 2 web service, if not started
    service:
      name: apache2
      state: started

  # MySQL Configuration
  - name: Start MariaDB, if not started
    service: 
      name: mysql
      state: started

  # GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' IDENTIFIED BY 'mutillidae';
  - name: Set MariaDB root
    mysql_user:
      login_unix_socket: '/var/run/mysqld/mysqld.sock'
      user: root
      password: "{{ mariadb_root_password }}"
      check_implicit_admin: true
      host_all: yes
      priv: '*.*:ALL,GRANT'

# Set up Mutillidae database
  - name: Visit Mutillidae Database Set Up page
    uri:
      url: http://mutillidae.local/set-up-database.php
      return_content: yes
    register: this
    failed_when: "'database' not in this.content"

# Copy over the lab files
  - name: Copy the lab files into the Documents folder
    copy:
      src: '{{ lab_files_dir }}'
      dest: '/root/Documents'
      mode: '0755'

  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded

    - name: Restart Apache
      service:
        name: apache2
        state: restarted

    - name: Restart MariaDB
      service:
        name: mariadb
        state: restarted

